name: PremakeBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        configuration: [Release, ReleaseNaNBoxing]
    steps:
    - uses: actions/checkout@v4

    - name: Run premake to generate solution files
      run: .\vendor\bin\premake\premake5 vs2022
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.configuration}} ${{env.SOLUTION_FILE_PATH}}
